import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import esbuild from "esbuild";

const current_file_path = fileURLToPath(import.meta.url);
const project_root = path.resolve(path.dirname(current_file_path), "..");
const source_root = path.join(project_root, "src", "mangoselect");
const css_entry = path.join(project_root, "src", "styles", "mangoselect.css");
const i18n_source_root = path.join(project_root, "src", "i18n");
const dist_directory = path.join(project_root, "dist");
const dist_i18n_directory = path.join(dist_directory, "i18n");
const repository_url = "https://github.com/mynameispond/mangoSelect";

const module_files = [
  "00-bootstrap.js",
  "10-core.js",
  "20-remote-config.js",
  "30-ui-state.js",
  "40-callbacks.js",
  "50-selection.js",
  "60-remote-data.js",
  "70-render.js",
  "80-instance.js",
  "90-export.js"
];

function get_version(source) {
  const match = source.match(/\bvar\s+version\s*=\s*"([^"]+)"/);
  return match ? match[1] : "0.0.0";
}

async function read_mangoselect_source() {
  const source_parts = await Promise.all(
    module_files.map(async (file_name) => {
      const file_path = path.join(source_root, file_name);
      const source = await readFile(file_path, "utf8");
      return source.replace(/^\uFEFF/, "").trimEnd();
    })
  );

  return source_parts.join("\n\n");
}

await mkdir(dist_directory, { recursive: true });
await mkdir(dist_i18n_directory, { recursive: true });

const source = await read_mangoselect_source();
const version = get_version(source);
const shared_banner = `/*! mangoSelect v${version} | ${repository_url} | MIT License */`;
const unminified_banner = [
  "/*",
  " * mangoSelect",
  ` * ${repository_url}`,
  " * Built from src/mangoselect/* by scripts/build.mjs",
  " * Do not edit this file directly.",
  " */",
  ""
].join("\n");

await writeFile(path.join(dist_directory, "mangoselect.js"), `${unminified_banner}${source}\n`, "utf8");

const minified_js = await esbuild.transform(source, {
  charset: "utf8",
  loader: "js",
  minify: true,
  target: "es2018"
});

await writeFile(path.join(dist_directory, "mangoselect.min.js"), `${shared_banner}\n${minified_js.code}`, "utf8");

const build_jobs = [
  {
    entryPoints: [css_entry],
    outfile: path.join(dist_directory, "mangoselect.css"),
    bundle: true,
    minify: false,
    banner: { css: shared_banner }
  },
  {
    entryPoints: [css_entry],
    outfile: path.join(dist_directory, "mangoselect.min.css"),
    bundle: true,
    minify: true,
    banner: { css: shared_banner }
  },
  {
    entryPoints: [path.join(i18n_source_root, "en.js")],
    outfile: path.join(dist_i18n_directory, "en.js"),
    bundle: true,
    format: "iife",
    minify: false,
    banner: { js: shared_banner }
  },
  {
    entryPoints: [path.join(i18n_source_root, "th.js")],
    outfile: path.join(dist_i18n_directory, "th.js"),
    bundle: true,
    format: "iife",
    minify: false,
    banner: { js: shared_banner }
  }
];

await Promise.all(
  build_jobs.map((build_job) =>
    esbuild.build({
      charset: "utf8",
      target: ["es2018"],
      logLevel: "info",
      ...build_job
    })
  )
);
